# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 831f36334e75a2b8624f7c445787456e287f97e3e5ad53e4f2ff0d07268370df5b224d63d39d93c99ed583db8a18e518ead082f218dbc0a6291f104dfaea6d38

test:
  secret_key_base: d9623db9d5dd837013370d567a110a2e00929378d9470809cb7a33f060e749f049d7eba12fc9a8e6e5e4736e20f5c38fab85f60c9e24df2d101f6752eaa209e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
